#!/bin/bash

IMG_IN=/tmp/in
IMG_OUT=/tmp/out
IMG_REJECT=/tmp/reject
CAPTURE_MOSAIC=/tmp/out/mosaic.jpg

if [ "xxx$2" == "xxx" ]; then
  echo "Missing arg: file.jpg pseudo"
  exit 1
fi

if [ ! -f "$1" ]; then
  echo "$1 does not exist."
  exit 3
fi
set -x
PSEUDO=$2
# getting file name
s=$1
s="${s##*/}"
IMAGE="${s%.*}"

mkdir ${IMG_IN} ${IMG_OUT} ${IMG_REJECT} 2>/dev/null
convert $1 ${IMG_IN}/${IMAGE}.jpg

/usr/local/autocrop/bin/autocrop --input ${IMG_IN} --output ${IMG_OUT} --reject ${IMG_REJECT} --height 600 --width 450

# calcul du svg
cartoon -p 30 -n 40 -e 6 -m 1 "${IMG_OUT}/${IMAGE}.jpg" "${IMG_OUT}/${IMAGE}.png"

convert "${IMG_OUT}/${IMAGE}.png" -flatten -colorspace Gray -negate -edge 2 -negate -threshold 50% "${IMG_OUT}/${IMAGE}.ppm"

# on insert le pseudo et rotate
convert -pointsize 70 -font "From-Street-Art" label:${PSEUDO} -threshold 50% -trim +repage -bordercolor white -border 5x5  "${IMG_OUT}/text.ppm"
convert "${IMG_OUT}/${IMAGE}.ppm" -gravity center "${IMG_OUT}/text.ppm" -append -rotate -90 "${IMG_OUT}/image_text.ppm"

# convert -rotate -90 ${IMG_OUT}/image_text.ppm ${IMG_OUT}/image_text_rotated.ppm
# potrace -s ${IMG_OUT}/image_text_rotated.ppm -b svg --unit 100 --turdsize 5 --turnpolicy black -o ${IMG_OUT}/${IMAGE}.svg

potrace -s "${IMG_OUT}/image_text.ppm" -b svg --unit 100 --turdsize 5 --turnpolicy black -o "${IMG_OUT}/image_text.svg"
svg2gcode -B -F -w 280 -t 1 "${IMG_OUT}/image_text.svg" "${IMG_OUT}/${IMAGE}.tmp.gcode"
cat "${IMG_OUT}/${IMAGE}.tmp.gcode" | uniq > "${IMG_OUT}/${IMAGE}.gcode"
