#!/bin/bash

IMG_IN=/tmp/in
IMG_OUT=/tmp/out
IMG_REJECT=/tmp/reject
CAPTURE_MOSAIC=/tmp/out/mosaic.jpg

if [ ! -f "$1" ]; then
  echo "$1 does not exist."
  exit 3
fi


# getting file name
s=$1
s="${s##*/}"
IMAGE="${s%.*}"
svgwide=${2:-280}

mkdir ${IMG_IN} ${IMG_OUT} ${IMG_REJECT} 2>/dev/null
convert $1 ${IMG_OUT}/${IMAGE}.jpg

convert ${IMG_OUT}/${IMAGE}.jpg -noise 5 -resize 600 ${IMG_OUT}/${IMAGE}.pbm

# calcul du svg
python /usr/local/bin/tspart.py --max-segments=5000 --runs=1 ${IMG_OUT}/${IMAGE}.pbm

/usr/local/bin/svg2gcode -B -F -w ${svgwide} -t 1 "${IMG_OUT}/${IMAGE}.svg" "${IMG_OUT}/${IMAGE}-tsp-${svgwide}.svg2gcode.gcode"
/usr/local/bin/svg2gcode-filrouge -B -F -w ${svgwide} -t 1 "${IMG_OUT}/${IMAGE}.svg" "${IMG_OUT}/${IMAGE}.tmp.gcode"
cat "${IMG_OUT}/${IMAGE}.tmp.gcode" | uniq > "${IMG_OUT}/${IMAGE}-tsp-${svgwide}.filrouge.gcode"


