#!/bin/bash

IMG_IN=/tmp/in
IMG_OUT=/tmp/out
IMG_REJECT=/tmp/reject

if [ ! -f "$1" ]; then
  echo "$1 does not exist."
  exit 3
fi

# getting file name
s=$1
s="${s##*/}"
IMAGE="${s%.*}"
svgwide=${2:-280}

mkdir ${IMG_IN} ${IMG_OUT} ${IMG_REJECT} 2>/dev/null
convert $1 ${IMG_OUT}/${IMAGE}.jpg

(cd ~/github/tspart && ./tspart_devfest ${IMG_OUT}/${IMAGE}.jpg 1 3000 ${IMG_OUT}/${IMAGE}.svg 2>/dev/null)

/usr/local/bin/svg2gcode -B -F -w ${svgwide} -t 1 "${IMG_OUT}/${IMAGE}.svg" "${IMG_OUT}/${IMAGE}-hilbert-${svgwide}.svg2gcode.gcode"
/usr/local/bin/svg2gcode-filrouge -B -F -w ${svgwide} -t 1 "${IMG_OUT}/${IMAGE}.svg" "${IMG_OUT}/${IMAGE}.tmp.gcode"
cat "${IMG_OUT}/${IMAGE}.tmp.gcode" | uniq > "${IMG_OUT}/${IMAGE}-hilbert-${svgwide}.filrouge.gcode"



